# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1229ec82924a1328e042286e568044774e29918a02f7b7a3400d7952786ae2b434d03c8cb81ff89485a4c2961fecdfd9eae4e224e6ea8d0c98e61a4d9bdd387e

test:
  secret_key_base: 78cf9da332e42705024c2e924748646fa7ca11f0e8d923f6f36202d4351fa90c0877008e45b86a8ad8debc79e915fcb632a142236466e71fcdeea4774bd0d323

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
